#!/bin/bash -e
log-helper level eq trace && set -x

set -o pipefail

# Usage:
# packages-install [package 1] [package 2] ...

ARGS="$*"

log-helper info "Install packages: ${ARGS}"
eval apk -q add "${ARGS}" 2>&1 | log-helper info
